### ISSUE TITLE
{"ok":false,"error":"invalid_auth"}%

### ISSUE THREAD

**Issue by jitendravyas** [outsideris/slack-invite-automation#1]
I have generated token at this page https://api.slack.com/web#auth

But getting error when I try to confirm it

![1 zsh c32zo](https://cloud.githubusercontent.com/assets/77309/5852413/5d8129e2-a23c-11e4-9ab5-655b2856dd61.jpg)

**Comment by outsideris** [comment]
You have to replace `TOKEN` part with your actual token.
