### ISSUE TITLE
Error scope_missing on submit of email address Heroku 

### ISSUE THREAD

**Issue by cfontan** [outsideris/slack-invite-automation#103]
I read the comments in https://github.com/outsideris/slack-invite-automation/issues/8  and created a new user, added admin, created new app and generated an API token with Admin in the scope to no avail. 

https://ladevs.herokuapp.com/invite

**Comment by bkhouri** [comment]
I don't know what our issue is, but I personally had to issue a Legacy tokens to get the app working.

**Comment by cfontan** [comment]
Thank you for that tip.. That worked!
