### ISSUE TITLE
Dutch locale

### ISSUE THREAD

**Issue by ghost** [outsideris/slack-invite-automation#109]
I translated this for you in Dutch ; can you add ?

{
  "HEADER": "Voer uw email adres in om deel te nemen aan %s op Slack!",
  "ENTER_EMAIL": "Voer uw email adres in",
  "ENTER_TOKEN": "Voer het token in dat u kreeg bij uw uitnodiging",
  "TITLE": "Neem deel aan de %s gemeenschap op Slack!"
}

**Comment by outsideris** [comment]
Could you make a pull request?

**Comment by outsideris** [comment]
Closed by https://github.com/outsideris/slack-invite-automation/pull/110
