### ISSUE TITLE
How to contribute a new translation?

### ISSUE THREAD

**Issue by aboros** [outsideris/slack-invite-automation#111]
Thank you for this great app, i really like it. We use it for invites for a small Hungarian tech community channel. It would be nice if there was a Hungarian translation available, which i am happy to contribute, i am just not too familiar with apps like this one, so i would really appreciate a little guidance about how to add new translations.

Thanks, 
Adam

**Comment by outsideris** [comment]
I close this because PR is opened. I think you know it now.
