### ISSUE TITLE
SVG Badge for GitHub README.md

### ISSUE THREAD

**Issue by rwieruch** [outsideris/slack-invite-automation#114]
Are there any plans to implement a SVG Badge that can be used in a GitHub README.md of a project afterward?

Like in this project: https://github.com/parcel-bundler/parcel
And this badge: https://slack.parceljs.org/badge.svg

Would love to see that feature for this project too :)

**Comment by outsideris** [comment]
Do you want a SVG badge of this project to use it on other websites? What kind of information on badge do you want? user count?

**Comment by rwieruch** [comment]
Yes. GitHub README.md would be most important though. Otherwise it may just say: [Slack 18/213] Do you think it is feasible?

**Comment by outsideris** [comment]
Yes, I think it is feasible because slackin already has it. I should read slack's API document.

**Comment by rwieruch** [comment]
Would be great to have it! I assume many people would use it. There are already a couple of my own repositories where I would use it :)

**Comment by trp07** [comment]
Does this feature work?  I just deployed this to heroku, but I'm not seeing the badge appear.  If I understood it correctly, is the badge url supposed to be:

https://myAppName.herokuapp.com/badge.svg  (not my actual url)

Thanks!  Great product by the way!  It was very easy to deploy.  Thank you for putting it together!

**Comment by trp07** [comment]
Nevermind.  I had an issue with the token.  It is working now.  Great Project.  Thank you for making this!

**Comment by outsideris** [comment]
@trp07 Good!

**Comment by securisec** [comment]
@outsideris any tip on where to put the badge.svg tag in source? i am not fully sure.

**Comment by crosbygw** [comment]
I noticed our badge always displays zero for number of active users: IE 0/2059. 
Anyone else have this issue?
Any help would be appreciated.

**Comment by rwieruch** [comment]
I have this issue a few months now. Thought it would be my setup, but I am curious if others run into this as well!

**Comment by tgamblin** [comment]
I also have the 0/nusers issue.
