### ISSUE TITLE
Setting up API Gateway + Lambda + CloudFormation

### ISSUE THREAD

**Issue by gabedeko** [outsideris/slack-invite-automation#121]
Hello,

I am fairly new to the technologies listed in the title of this issue but I have been using AWS for things like S3 and EC2 from some time now. So far I've successfully created an API in API Gateway with the `api-swagger-template.json` file but have also been going through the process of setting up Lambda and CloudFormation for some time now but keep getting stuck. Would someone be kind enough to provide some sort of walk-through for this purpose. I've tried many others but the purpose of those apps are different which means they're set up differently. The documentation in the repo doesn't go very much in depth on how to deploy the app with AWS.

Are these even necessary fro deploying the app with AWS?

Much appreciated.

**Comment by outsideris** [comment]
@lafiosca Could you help this?

**Comment by gabedeko** [comment]
Thanks @outsoderis I decided to use AWS Serverless Express which actually worked perfectly!

https://github.com/awslabs/aws-serverless-express

**Comment by outsideris** [comment]
@gabedeko Great!

**Comment by lafiosca** [comment]
@gabedeko Did you mean that you deployed this project using that, or were you building an app of your own? The directions in the README should be sufficient for deploying this project, but if they were not, I'd like to know where the gaps are. Thanks.

**Comment by gabedeko** [comment]
@lafiosca I was mostly referring to the confusing UI of AWS and their multiple apps. 

In number 3 of your steps you say to 

> Run aws/deploy.sh to create the CloudFormation stack and deploy your application, outputting the URL

Maybe it's jut me but it doesn't seem very obvious what I'm running that on or how one should go about doing it.

**Comment by lafiosca** [comment]
Thanks for the feedback, @gabedeko. Honestly, the directions are a bit brief, but that step relies on the pre-requisite mentioned before the list: "If you have an AWS account and have already installed and configured the AWS CLI tool". There could certainly be more detail added to explain that part, or at least a link to further documentation. If you have the AWS CLI tool set up locally on a computer or server, from that same environment you can run the deploy shell script to execute the appropriate AWS CLI commands.
