### ISSUE TITLE
Slack Invite As a Service

### ISSUE THREAD

**Issue by ripper234** [outsideris/slack-invite-automation#18]
This service is cool!

What would be even cooler is if I as a user won't have to install anything.
Can you make that magic work?

**Comment by outsideris** [comment]
Providing as a service needs server resourses. Does Heroku deploy button is not enough? Or, do you have any idea about that?

**Comment by ripper234** [comment]
Hmm, I just did the Heroku deploy - never imagined it would be so easy!
I guess this feature is nice to have but really really not critical, since Heroku deploy is so easy.

Closing for now.
