### ISSUE TITLE
Error entering an email address

### ISSUE THREAD

**Issue by ripper234** [outsideris/slack-invite-automation#19]
After deploying, I get

"Failed! Something has gone wrong. Please contact a system administrator."

I see nothing in our logs

![image](https://cloud.githubusercontent.com/assets/172282/12439721/90206732-bf3c-11e5-9da7-523d2ac84d20.png)

**Comment by synth** [comment]
This message is a bit cryptic, but if you look at the code, its thrown when the error comes back as "invalid_auth". In my case, I copy/pasted the token wrong; for some reason when I c/p'd it, the text also contained "Reissue token" and this wasn't visible to me by looking at heroku's settings in the web ui. You can see it if you "Edit" the setting however.

**Comment by outsideris** [comment]
@synth is right. I guess your token is wrong.

**Comment by ripper234** [comment]
Thanks, I'll check that.
