### ISSUE TITLE
Error with email

### ISSUE THREAD

**Issue by Oxyrus** [outsideris/slack-invite-automation#20]
I can't manage the app to work, I tried deploying it directly to Heroku but it didn't work.

```
"Failed! Something has gone wrong. Please contact a system administrator."
```

Is what I get, I tried then cloning the application directly from Heroku and setting up my configuration in the config.js file, then deployed it again and still didn't work.

What could be causing it?

Thanks!

**Comment by Oxyrus** [comment]
## solved

I deleted the application and deployed it again and worked!

**Comment by outsideris** [comment]
@Oxyrus Good!
