### ISSUE TITLE
Token?

### ISSUE THREAD

**Issue by tomatohunter** [outsideris/slack-invite-automation#28]
Is the "token" still called token on Slack? There is nothing called "token" in https://api.slack.com/web#auth. All I can do is register an app and generate api key/secret...with which the app fails with {"ok":false,"error":"invalid_auth"} no matter if the app was registered by owner or by admin user.

**Comment by outsideris** [comment]
I think they still call it as "token".

<img width="688" alt="2016-03-16 21 23 54" src="https://cloud.githubusercontent.com/assets/390146/13812108/7385283a-ebbd-11e5-9405-abafa2fa6263.png">

Is your account owner for slack? (not admin user) I expect many issues are raised on this repository if Slack change the policy.

**Comment by kyleschmolze** [comment]
For anyone else who ends up here: Yes, you just use the test tokens, even though Slack tries to convince you never you use your test tokens for any real apps.

**Comment by outsideris** [comment]
@kyletns 👍
