### ISSUE TITLE
Faild Paid only

### ISSUE THREAD

**Issue by jitendravyas** [outsideris/slack-invite-automation#3]
It seems that Slack has disabled auto subscribe facility. Every body is getting "Failed, paid only" message when user enter email and press enter

**Comment by darrellsilver** [comment]
Yeah – just had this error, too. On both a new team and an old one.

**Comment by outsideris** [comment]
Sadly, [slack blocked this api](https://twitter.com/levelsio/status/565922661994201088).

**Comment by yhsiang** [comment]
[it works again](https://twitter.com/levelsio/status/566680559405903873)

**Comment by outsideris** [comment]
@yhsiang I comfirmed it. Thank you for noticing it.
