### ISSUE TITLE
Load Google fonts over https

### ISSUE THREAD

**Issue by jlegrone** [outsideris/slack-invite-automation#32]
Necessary to fix this mixed content error:
`Mixed Content: The page at 'https://<app-name>.herokuapp.com/invite' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lato:300,400,700,900,700italic|Open+Sans:700italic,400,600,300,700,800'. This request has been blocked; the content must be served over HTTPS.`

**Comment by sinesiobittencourt** [comment]
Hello,
I modified the http to https, waiting for the master validate.

Thanks.

**Comment by outsideris** [comment]
resolved in #43
