### ISSUE TITLE
Guest invite

### ISSUE THREAD

**Issue by ChappIO** [outsideris/slack-invite-automation#38]
Hello, would it be possible to use this app to invite guests?

**Comment by outsideris** [comment]
@thomasbiesaart  Did you mean to invite guest members or restricted members not full members? If so, it is not possible now. But I guess you can do it if you dig the slack API.

**Comment by ChappIO** [comment]
I found it. You can invite single channel guests by only submitting one channel and setting the 'ultra_restricted' property to 1. Multi channel guests have the 'restricted' property to 1 instead. We decided to no longer use slack for our chat but I figured i'd share the information.

**Comment by outsideris** [comment]
I got it. Thank you for your feedback.
