### ISSUE TITLE
Getting Failed missing_scope on /invite page

### ISSUE THREAD

**Issue by igauravsehrawat** [outsideris/slack-invite-automation#4]
![missing_scope](https://cloud.githubusercontent.com/assets/3696327/6811046/1f0c9fbe-d28b-11e4-80b0-42437d3fba7a.png)

**Comment by jeremychu** [comment]
If you run the curl example you'll probably see something like this:
{"ok":false,"error":"missing_scope","needed":"admin","provided":"identify,read,post,client"}

I haven't confirmed it although I suspect this means the bearer token you've generated isn't from a Team Admin user.

**Comment by outsideris** [comment]
It looks slack invite api is changed. I will check it.

**Comment by igauravsehrawat** [comment]
@jeremychu you are absolutely correct, didn't had admin permission .
@outsideris slack api is good.

**Comment by outsideris** [comment]
:+1:

**Comment by jonchui** [comment]
@jeremychu @outsideris we're getting the same error, but i'm an "Owner" and "Admin" of the team. how do i make myself "team admin"?

![image](https://cloud.githubusercontent.com/assets/204868/24214120/b1945d78-0ed8-11e7-99f4-29ed3b127cc4.png)
