### ISSUE TITLE
invite email not being sent

### ISSUE THREAD

**Issue by v2k** [outsideris/slack-invite-automation#40]
Set this up on heroku, everything appears fine; curl test works.  It never sends the invite email.

SLACK_TOKEN set
INVITE_TOKEN empty

Nothing of note in the logs.

**Comment by outsideris** [comment]
What did you means the invite email? There is no email system. @v2k

**Comment by v2k** [comment]
How does it invite the user then?

**Comment by outsideris** [comment]
You can share the url of it in your community channel. It just make inviting someone into Slack without admin's approval.
