### ISSUE TITLE
Is it bot-proof?

### ISSUE THREAD

**Issue by jackmcdade** [outsideris/slack-invite-automation#63]
We used Slackin for our self-invite system and it got hit by a script bot and mass invited 9k email addresses to our account. There were a lot of angry people on Twitter that day.

Is there anything to throttle/prevent that from happening with this project?

**Comment by outsideris** [comment]
Now, there is now preventing bot system. It is a good point. We need it.

**Comment by julianschiavo** [comment]
Recaptcha maybe?

**Comment by GiacomoLaw** [comment]
Hoping to see one. :smile:

**Comment by julianschiavo** [comment]
check out:

https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fflexd%2Fslackinviter

It's a clone of slackin but in go to use 10x less memory and add recaptcha.

**Comment by outsideris** [comment]
[recaptcha](https://www.google.com/recaptcha/intro/index.html) is a gool solution.

**Comment by GiacomoLaw** [comment]
How can I add this to it?

**Comment by julianschiavo** [comment]
this is a github repo that is a clone of slackin + racaptcha:

http://github.com/flexd/slackinviter

**Comment by GiacomoLaw** [comment]
Can I add this to my existing server?

https://evernote-community.herokuapp.com

**Comment by outsideris** [comment]
@GiacomoLaw You should your site on recaptcha and then follow google's instruction. As I remember, it is easy to use.

**Comment by GiacomoLaw** [comment]
Okay, thank you!

**Comment by GiacomoLaw** [comment]
@jaspergreenham I added it, however do not see the recaptha.

**Comment by julianschiavo** [comment]
I checked the link you gave above, I see the recaptcha, is it working now?

(If you want to change css, I made one changing css, you can look at mine to see how: applenc.herokuapp.com).

**Comment by julianschiavo** [comment]
You have to use the link I gave you, I also was not able to integrate into an existing inviter.

**Comment by GiacomoLaw** [comment]
Managed to work it, thank you!

**Comment by O1O1O1O** [comment]
The reCaptcha is nice but I like the invite code - I don't want random people to join unless they have the invite code.  I don't see a bot guessing a well-chosen invite code unless someone leaks it or gets their email hacked.  A combo of both would be awesome.

**Comment by outsideris** [comment]
@O1O1O1O There is already `inviteToken`, see [config](https://github.com/outsideris/slack-invite-automation#configjs). I think this feature protected a page that doesn't use the invite token.

**Comment by rynomster** [comment]
Our community was getting overwhelmed by bots so we added #106, in case anyone wants to use it.
