### ISSUE TITLE
Deploy to Heroku workers die 

### ISSUE THREAD

**Issue by bikrdotnet** [outsideris/slack-invite-automation#73]
I keep having to restart the app as the heroku workers die. Is this a known issue with a fix? This is a stock deploy to heroku instance and just doesn't stay alive

**Comment by morenoh149** [comment]
you need to ping the dyno every so often to prevent it from idling, there are several solutions here https://stackoverflow.com/questions/5480337/easy-way-to-prevent-heroku-idling Not an issue
