### ISSUE TITLE
Error:Error: getaddrinfo ENOTFOUND https https:443

### ISSUE THREAD

**Issue by OKNoah** [outsideris/slack-invite-automation#77]
When deploying on Dokku, I get this error after entering an email address and hitting enter.

```
Error:Error: getaddrinfo ENOTFOUND https https:443
```

It's just a white page with black text, the browser location is at `/invite`.

Would this happen if my token wasn't from an admin account or something?

**Comment by outsideris** [comment]
Can you show me the stacktrace?

**Comment by MichMich** [comment]
For anyone having the same issue. Make sure the SLACK_URL only contains the domain (eg: mychannel.slack.com) without the `http://` part.
