### ISSUE TITLE
Invitation fails with Failed! missing_scope

### ISSUE THREAD

**Issue by kevin-lee** [outsideris/slack-invite-automation#8]
I tested the invitation feature with a few different email addresses but none has succeeded.

I get `Failed! missing_scope` when using this app and the following result if I use `curl` command provided in the `README.md`.

``` json
{"ok":false,"error":"missing_scope","needed":"admin","provided":"identify,read,post,client"}
```

I've already checked https://api.slack.com/tokens page and it says that the token has `admin` scope.

**Comment by kevin-lee** [comment]
I'm not quite sure but it probably has something to do with Slack API itself.
https://twitter.com/SlackAPI/status/644943274558533632

**Comment by kevin-lee** [comment]
Unfortunately, it's official now. :disappointed: Slack says it's an undocumented method so not supported. They're working on an alternative to the method but has no firm timeline for its release. sigh... :disappointed: I'm not sure what else can be done at this point. :(

**Comment by ghost** [comment]
I hit the same problem - the code used to work but, when I saw this issue, I checked and found the same problem. Seems as if the tokens issued at https://api.slack.com/web#auth don't have the required "admin" in their scope list.

There is a work around, but I'm not sure if it abides by Slack's terms of service.  With a browser, log into Slack and go through the workflow to send an invite to someone.  Use the browser's "inspect element" to look at the request when you hit the invite button.  If you look in the "form data", you should see a token.  For me, this token works with the slack-invite-automation code.

**Comment by outsideris** [comment]
@hackscribble Yes, you are right. I fix it in local. I will update it soon.

**Comment by kevin-lee** [comment]
I can confirm that it's fixed. It works well with the admin key not the owner one.
@outsideris, thanks a lot!

**Comment by ivanoats** [comment]
How do we get the admin key instead of the owner one? Is there a URL to visit? 

Thanks for fixing this BTW 😀

**Comment by outsideris** [comment]
@ivanoats In `/admin`, you should make any user as admin. Then you sign in as that user and generate the token.

**Comment by lpommers** [comment]
I just saw this issue again with an admin token... has this resurfaced for anyone else?

**Edit**: I had to ask for both `admin` and `client` in the scope when doing oauth
