### ISSUE TITLE
Is there a way to change background when deployed directly to Heroku?

### ISSUE THREAD

**Issue by stefek99** [outsideris/slack-invite-automation#80]
Just wondering if there is such an option.

In the meanwhile cloned the repo, change a few bits and then manually deploy.

**Comment by ghost** [comment]
I'm trying to do the same. I also tried cloning the git repository from heroku, but it says "you seem to have cloned an empty repository". 
I can't see any files there.

**Comment by rcstr** [comment]
Same here, any luck?

**Comment by xuanzi23** [comment]
waiting for the answer.

**Comment by sabhiram** [comment]
Check out my fork of the project, it should have provisions to supply your own custom css for the landing page.

**Comment by csethna** [comment]
Somewhat similar, I want to add a link to our code of conduct underneath the email field. Is there an "index" file or something that I'm missing?

**Comment by AnEmortalKid** [comment]
@csethna  maybe around here? https://github.com/outsideris/slack-invite-automation/blob/master/views/index.jade#L18

**Comment by AnEmortalKid** [comment]
So, I cloned from git and then pushed to heroku. I Found that the background is named `bg.jpg` and is a 3000x1024 image. Located in public/images. If you replace that with an image called bg.jpg it should load:

![image](https://user-images.githubusercontent.com/3474369/31366381-33f1987a-ad36-11e7-9d0e-6cc187724443.png)

In fact, you can add any image named bg.jpg it looks like (and muck around with the css):
![image](https://user-images.githubusercontent.com/3474369/31366483-d3b1c0d8-ad36-11e7-88d5-72a0b783d41d.png)

**Comment by morenoh149** [comment]
@stefek99 is your issue solved?

**Comment by stefek99** [comment]
> So, I cloned from git and then pushed to heroku.

I think I did exactly the same.

**Comment by morenoh149** [comment]
you'd need to clone, make a change, commit the change to version control, and then do `git push heroku master` as heroku usually depends on git for updates

**Comment by stefek99** [comment]
The issue says:

> directly to Heroku

The description of the issue:

> In the meanwhile cloned the repo, change a few bits and then manually deploy.

I do not remember the exact process of deploying, maybe there is a place for a config variable here or there... (such as an API key)

Directly to Heroku means clicking on a button "deploy to Heroku", deploying directly to Heroku:

![image](https://user-images.githubusercontent.com/249703/41900434-053e1a2e-792f-11e8-8111-8861b6a6b0cb.png)

No worries, more often than not people tell me that I'm **autistic psychopath** but I don't have bad intentions, only good vibes.

**Comment by morenoh149** [comment]
@stefek99 indeed, I too found out I had to associate the heroku app with a fork of the repo after the fact, we've improved the readme at https://github.com/outsideris/slack-invite-automation#associate-fork-with-heroku recently. Hope it helps.
