### ISSUE TITLE
Getting the missing_scope error in admin account

### ISSUE THREAD

**Issue by fstltna** [outsideris/slack-invite-automation#87]
I created a admin user, not owner user, and tried to create the API key but I get the missing_scope error anyway. Any help on this? I'm using the latest version from this repo...

**Comment by 1mintee1** [comment]
Same, any update?

**Comment by outsideris** [comment]
Did you see #83 ?

**Comment by outsideris** [comment]
I updated README. Please check https://github.com/outsideris/slack-invite-automation#issue-token .
