### ISSUE TITLE
Failed! missing_scope

### ISSUE THREAD

**Issue by pthieu** [outsideris/slack-invite-automation#9]
Clicked the deploy button and quickly set up config vars on heroku. When I test with account, it gives me a `Failed! missing_scope` error. This is on newest code.

**Comment by outsideris** [comment]
Use the token generted by an admin user, not an owner user. see #8

**Comment by pthieu** [comment]
Confirmed working. Steps:
1. Create new user
2. Invite new user to Slack team
3. Make new user admin
4. Get API token from new user after admin rights granted
5. Switch the config over to new token

Not sure why we have to do this. But I guess Slack's doing some weird update.

**Comment by rkamudhan** [comment]
@pthieu @outsideris How you resolved it? I create a new user and added it as admin and given API token of it in Heroku. But I am still getting the error "Failed! missing_scope"
