### ISSUE TITLE
Azure Deploy issue

### ISSUE THREAD

**Issue by ghost** [outsideris/slack-invite-automation#91]
Hi, I got issue during deploy via Azure Deploy:
The request content was invalid and could not be deserialized: 'Could not find member 'default' on object of type 'TemplateInputParameter'. Path 'properties.template.parameters.siteLocation.default', line 15, position 21.'.

For your information I used all default values and I added tokens, slack team name.

**Comment by iloabn** [comment]
I'm receiving the same issue when trying to deploy to Azure.

Is there any other information that is needed from us that are experiencing the issue or some tips on where to start when troubleshooting it?

**Comment by outsideris** [comment]
fixed in 1e25ee648a89bc8ee7b05db3510e7ac55dfad1c1
