### ISSUE TITLE
Vulnerable Node.js

### ISSUE THREAD

**Issue by frenchmouss** [outsideris/slack-invite-automation#97]
Juste received a mail from Heroku warning the node.js used for the application may be outdated and as such at risk of DoS attacks.
Do we know if the application is up to date? 
Thanks in advance!

**Comment by shiftplusplus** [comment]
Email text:

> You are receiving this email because you run at least one Node.js application on Heroku.The Node.js team has announced that a high severity remote Denial of Service (DoS) Constant Hashtable Seeds vulnerability in Node.js versions 4.x through 8.x has been patched in the following versions: 4.8.46.11.17.10.18.1.4
> Detecting if you're vulnerable from the Heroku CLI
`$ heroku run node -v -a APPNAME`
> If your version is less than what's listed above, you will need to upgrade. 
> Upgrading
> If your application specifies a Node.js version in the engines section of your package.json, you will first need to update it to the appropriate version listed above. See this devcenter article on [specifying](http://hello.heroku.com/e/36622/t-specifying-a-node-js-version/cqwb5b/642624333) a Node.js version for details.
> To upgrade, you’ll need to push a new commit to your app, which will cause a deploy. If you don’t want to push any actual changes, this commit can be empty:
`$ git commit --allow-empty -m “upgrade Node.js version"$ git push heroku master`
> Verifying that you're running a fixed version of Node.js
> After your application has been deployed, you can verify that the new version is installed by running:
`$ heroku run node -v -a APPNAME`
> This will show one of the version strings from above.If you have any questions, please contact us at http://hello.heroku.com/e/36622/2017-07-12/cqwb5d/642624333

**Comment by millerjp** [comment]
Yeah - I got this also. The app is running on a vulnerable version for sure so needs to be updated. Do we know if this is going to happen or should I fork it?

**Comment by chemix** [comment]
I think application is fine, but node version at heroku is my problem. Via console I get information that node is in v6.10.1 version. But I don't know how to node.js update to stable secure version, because the manual in email from heroku doesn't work for me. I clicked at "Heroku deploy" button. Any suggestion?

**Comment by outsideris** [comment]
It's is heroku issues rather than this application. you can re-deploy it on heroku.
